version: 1.0.0.{build}

image: Visual Studio 2022

pull_requests:
  do_not_increment_build_number: true

before_build:
  - nuget restore "Screamer.sln"
  - choco install "msbuild-sonarqube-runner" -y
  - SonarScanner.MSBuild.exe begin /k:"Screamer" /o:"mprokushenkov" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="3c28d4b623cea1a15afefecfda86f700818c8919"
  
build:
  project: Screamer.sln
  verbosity: minimal

test:
  assemblies:
    only:
    - tests\**\bin\**\*UnitTests.dll
    
after_test:
  - SonarScanner.MSBuild.exe end /d:sonar.login="3c28d4b623cea1a15afefecfda86f700818c8919"
